---
title: "Movie Theater Insights Data Analysis"
output: html_document
date: "2024-12-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Project Resources


```{r}

# Packages used

library(dplyr)
library(ggplot2)
library(patchwork)
library(hms)
library(effsize)
library(car)


# Data Repository

library(readxl)
Galaxy_Theatres_Movie_Ticket_Characteristics_For_Data_Analysis_ <- read_excel(
  "Galaxy Theatres Movie Ticket Characteristics (For Data Analysis).xlsx")



# The title for the dataset was changed for simplicity.
# R has trouble reading 'Screening Showtime' as a numeric value, so let's fix that.

MovieTheaterDataSet <- Galaxy_Theatres_Movie_Ticket_Characteristics_For_Data_Analysis_

MovieTheaterDataSet$`Screening_Showtime`<- as_hms(MovieTheaterDataSet$`Screening_Showtime`)
View(MovieTheaterDataSet)



```

# Brief Statistics


```{r}

# Brief Summary of DataSet

Base_TP_Stats <- MovieTheaterDataSet %>%
  summarize(
    Min = min(Base_Ticket_Price, na.rm = TRUE),
    Q1 = quantile(Base_Ticket_Price, 0.25, na.rm = TRUE),
    Median = median(Base_Ticket_Price, na.rm = TRUE),
    Mean = mean(Base_Ticket_Price, na.rm = TRUE),
    Q3 = quantile(Base_Ticket_Price, 0.75, na.rm = TRUE),
    Max = max(Base_Ticket_Price, na.rm = TRUE)
  )


Final_TP_Stats <- MovieTheaterDataSet %>%
  summarize(
    Min = min(Final_Ticket_Price, na.rm = TRUE),
    Q1 = quantile(Final_Ticket_Price, 0.25, na.rm = TRUE),
    Median = median(Final_Ticket_Price, na.rm = TRUE),
    Mean = mean(Final_Ticket_Price, na.rm = TRUE),
    Q3 = quantile(Final_Ticket_Price, 0.75, na.rm = TRUE),
    Max = max(Final_Ticket_Price, na.rm = TRUE)
  )


# Counts

DiscountedCount <- MovieTheaterDataSet %>%
  group_by(Discounted_Ticket) %>%
  summarise(Count = n())

DiscountedCount


SpecialEventCount <- MovieTheaterDataSet %>%
  group_by(Special_Event_Pricing) %>%
  summarise(Count = n())

SpecialEventCount



SpecialProgramCount <- MovieTheaterDataSet %>%
  group_by(Special_Program) %>%
  summarise(Count = n())

SpecialProgramCount




```





# Data Visualizations


```{r}

# Single Linear Regression Model

lm_model <- lm(Final_Ticket_Price ~ Base_Ticket_Price, data = MovieTheaterDataSet)
summary(lm_model)

# Scatterplot of Relationship between Base and Final Ticket Prices

plot(MovieTheaterDataSet$Base_Ticket_Price, MovieTheaterDataSet$Final_Ticket_Price,   
xlab = "Base Ticket Price", ylab = "Final Ticket Price", main =   
"Relationship Between Base and Final Ticket Prices")
abline(lm_model)

# Correlation Coefficient (p)

p <- cor(MovieTheaterDataSet$Base_Ticket_Price, MovieTheaterDataSet$Final_Ticket_Price)
head(p)

# There is a strong positive correlation between Base and Final Ticket Prices.

```

```{r}

#### Bar Charts -- One Categorical Variable Against One Continuous Variable


### Group 1: Time-Related Variables


## Relationship Between Screening Dayparts and the Median Final Ticket Price

# Before visualizing data based on Screening Dayparts, 
# we need to manually alter the variable.
MovieTheaterDataSet$Screening_Daypart <- factor(
  MovieTheaterDataSet$Screening_Daypart, 
  levels = c("Matinee", "Evening"))


Plot1 <- ggplot(MovieTheaterDataSet, 
                aes(x = Screening_Daypart, 
                    y = Final_Ticket_Price, 
                    fill = Screening_Daypart)) +
  stat_summary(fun = "median", geom = "bar", 
               color = "black", width = 0.4, 
               position = position_dodge(width = 0.5)) +
  stat_summary(fun = "median", geom = "text", 
               aes(label = round(..y.., 2)), vjust = -0.5) +
  scale_fill_manual(values = c("lightblue", "steelblue", 
                               "dodgerblue", "darkblue")) +
  labs(title = "Median Final Ticket Price by Screening Daypart",
       x = "Screening Daypart", y = "Median Final Ticket Price",
       fill = "Screening Daypart")

Plot1

## Relationship Between Time Periods and the Median Final Ticket Price

# Before visualizing data based on Time Periods, 
# we need to manually alter the variable.
MovieTheaterDataSet$Time_Periods <- factor(
  MovieTheaterDataSet$Time_Periods, 
  levels = c("Morning", "Midday", "Dusk", "Night"))


Plot2 <- ggplot(MovieTheaterDataSet, 
                aes(x = Time_Periods, 
                    y = Final_Ticket_Price, 
                    fill = Time_Periods)) +
  stat_summary(fun = "median", geom = "bar", 
               color = "black", width = 0.4, 
               position = position_dodge(width = 0.5)) +
  stat_summary(fun = "median", geom = "text", 
               aes(label = round(..y.., 2)), vjust = -0.5) +
  scale_fill_manual(values = c("lightgreen", "seagreen", 
                               "darkgreen", "forestgreen")) +
  labs(title = "Median Final Ticket Price by Time Period",
       x = "Time Period", y = "Median Final Ticket Price",
       fill = "Time Periods")

Plot2


## Relationship Between Days of the Week and the Median Final Ticket Price

# Before visualizing data based on Days of the Week, 
# we need to manually alter the variable.
MovieTheaterDataSet$Day_of_the_Week <- factor(
  MovieTheaterDataSet$Day_of_the_Week, 
  levels = c("Monday 1", "Tuesday", "Wednesday", 
             "Thursday", "Friday", "Saturday", 
             "Sunday", "Monday 2"))


Plot3 <- ggplot(MovieTheaterDataSet, 
                aes(x = reorder(Day_of_the_Week, -Final_Ticket_Price), 
                    y = Final_Ticket_Price, fill = Day_of_the_Week)) +
  stat_summary(fun = "median", geom = "bar", 
               color = "black", width = 0.6) +
  stat_summary(fun = "median", geom = "text", 
               aes(label = round(..y.., 2)), hjust = -0.2,size = 3) +
  scale_fill_manual(values = c("Monday 1" = "#47126b", "Tuesday" = "#571089",    
    "Wednesday" = "#6411AD", "Thursday" = "#6D23B6", "Friday" = "#822FAF",     
    "Saturday" = "#973AA8", "Sunday" = "#AC46A1", "Monday 2" = "#C05299")) + 
  coord_flip() +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.1))) +
  labs(title = "Median Final Ticket Price by Day of the Week",
       x = "Day of the Week", y = "Median Final Ticket Price",
       fill = "Day of the Week") + 
  theme_minimal() +
  theme(axis.text.y = element_text(size = 10),
        axis.text.x = element_text(size = 10),
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(color = "gray90"),
        plot.margin = unit(c(1, 1, 1, 1), "cm"))


Plot3




### Group 2: Movie Characteristics


## Relationship Between Genre and the Median Final Ticket Price

# Before visualizing data based on Genre,
# we must manually alter the variable.
MovieTheaterDataSet$Genre <- factor(
  MovieTheaterDataSet$Genre, 
  levels = c("Concert", "Documentary", "Animation", "Horror", "Action", 
             "Anime", "Fantasy","Thriller", "Drama", "Comedy"))


Plot4 <- ggplot(MovieTheaterDataSet, 
                aes(x = reorder(Genre, -Final_Ticket_Price), 
                    y = Final_Ticket_Price, fill = Genre)) + 
stat_summary(fun = "median", geom = "bar", 
             color = "black", width = 0.6) +
stat_summary(fun = "median", geom = "text", 
             aes(label = round(..y.., 2)), vjust = -0.4) +
scale_fill_manual(values = c("#4CC9F0", "#4895EF", "#4361EE","#3F37C9","#3A0CA3",
                             "#480CA8", "#560BAD", "#7209B7", "#B5179E", "#F72585")) +
labs(title = "Median Final Ticket Price by Genre",
x = "Genre",
y = "Median Final Ticket Price",
fill = "Genre") +
theme_minimal() +
theme(axis.text.x = element_text(angle = 45, hjust = 1),
legend.position = "none")


Plot4


## Relationship Between Format and the Median Final Ticket Price


Plot5 <- ggplot(MovieTheaterDataSet, 
                aes(x = reorder(Format, -Final_Ticket_Price), 
                    y = Final_Ticket_Price, fill = Format)) +
  stat_summary(fun = "median", geom = "bar", 
               color = "black", width = 0.5) +
  stat_summary(fun = "median", geom = "text", 
               aes(label = round(..y.., 2)), vjust = -0.3) +
  scale_fill_manual(values = c("#640D14", "#800E13", "#AD2831")) +
  labs(title = "Median Final Ticket Price by Format",
       x = "Format",
       y = "Median Final Ticket Price",
       fill = "Format") +
  theme_minimal() +
  theme(legend.position = "right",
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 10),
    panel.grid.major.y = element_blank(), 
    panel.grid.major.x = element_line(color = "gray90"),
    plot.margin = unit(c(1, 1, 1, 1), "cm"))


Plot5


## Relationship Between Special Program and the Median Final Ticket Price

# Before visualizing data based on Special Program,
# we must manually alter the variable.

MovieTheaterDataSet$Special_Program <- factor(
  MovieTheaterDataSet$Special_Program, 
  levels = c("Flashback Cinema", "None", "AXCN", 
             "Studio Ghibli", "Unique", "Fathom Events"))


Plot6 <- ggplot(MovieTheaterDataSet, 
                aes(x = reorder(Special_Program, -Final_Ticket_Price),
                    y = Final_Ticket_Price, fill = Special_Program)) +
  stat_summary(fun = "median", geom = "bar", 
               color = "black", width = 0.7) +
  stat_summary(fun = "median", geom = "text", 
               aes(label = round(..y.., 2)), vjust = -0.2, size = 3) +
  scale_fill_manual(values = c("#FF4800", "#FF6000", "#FF7900",
                               "#FF8500", "#FF9E00","#FFB600")) +
  labs(title = "Median Final Ticket Price by Special Program",
       x = "Median Final Ticket Price",
       y = "Special Program",
       fill = "Special Program") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "right",
        panel.grid.major.y = element_blank(), 
        panel.grid.major.x = element_line(color = "gray90"),
        plot.margin = unit(c(1, 1, 1, 1), "cm"))


Plot6


## Relationship Between Age Rating and the Median Final Ticket Price

# Before visualizing data based on Age Rating,
# we must manually alter the variable.

MovieTheaterDataSet$Age_Rating <- factor(
  MovieTheaterDataSet$Age_Rating, 
  levels = c("G", "R", "PG", "NR", "TBD", "PG13"))


Plot7 <- ggplot(MovieTheaterDataSet, 
                aes(x = reorder(Age_Rating, -Final_Ticket_Price), 
                    y = Final_Ticket_Price, fill = Age_Rating)) +
  stat_summary(fun = "median", geom = "bar", 
               color = "black", width = 0.5) +
  stat_summary(fun = "median", geom = "text", 
               aes(label = round(..y.., 2)), 
               vjust = -0.3, size = 3.5) +
  scale_fill_manual(values = c("#143601", "#1A4301", "#245501",
                               "#538D22", "#73A942", "#AAD576")) +
  labs(title = "Median Final Ticket Price by Age Rating",
       x = "Age Rating",
       y = "Median Final Ticket Price",
       fill = "Age Rating") + 
  theme_minimal() +
  theme(legend.position = "right",
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    panel.grid.major.y = element_blank(), 
    panel.grid.major.x = element_line(color = "gray90"),
    plot.margin = unit(c(1, 1, 1, 1), "cm"))


Plot7




### Group 3: Customer Characteristics


## Relationship Between Ticket Type and the Median Final Ticket Price

# Before visualizing data based on Ticket Type, 
# we must manually alter the variable.
MovieTheaterDataSet$Ticket_Type <- factor(
  MovieTheaterDataSet$Ticket_Type, 
  levels = c("Adult", "Child", "Senior", "Admit One", "FC Promo"))

Plot8 <- ggplot(MovieTheaterDataSet, 
                aes(x = reorder(Ticket_Type, -Final_Ticket_Price), 
                    y = Final_Ticket_Price, fill = Ticket_Type)) +
  stat_summary(fun = "median", geom = "bar", 
               color = "black", width = 0.5) +
  stat_summary(fun = "median", geom = "text", 
               aes(label = round(..y.., 2)), 
               vjust = -0.3, size = 3.5) +
  scale_fill_manual(values = c("#590D22", "#A4133C", "#FF4D6D",
                               "#FF8FA3", "#FFB3C1")) +
  labs(title = "Median Final Ticket Price by Ticket Type",
       x = "Ticket Type",
       y = "Median Final Ticket Price",
       fill = "Ticket Type") +
 theme_minimal() +
  theme(legend.position = "right",
    axis.text.x = element_text(size = 11),
    axis.text.y = element_text(size = 10),
    panel.grid.major.y = element_blank(), 
    panel.grid.major.x = element_line(color = "gray90"),
    plot.margin = unit(c(1, 1, 1, 1), "cm"))

Plot8


## Relationship Between Purchase Method and the Median Final Ticket Price

Plot9 <- ggplot(MovieTheaterDataSet, 
                aes(x = reorder(Purchase_Method, -Final_Ticket_Price), 
                    y = Final_Ticket_Price, fill = Purchase_Method)) +
  stat_summary(fun = "median", geom = "bar", 
               color = "black", width = 0.6) +
  stat_summary(fun = "median", geom = "text", 
               aes(label = round(..y.., 2)), vjust = -0.5, size = 4) + 
  scale_fill_manual(values = c("Online" = "#6A0DAD",  
                               "In-Person" = "#DDA0DD" )) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.1))) +
  labs(title = "Median Final Ticket Price by Purchase Method",
       x = "Purchase Method",
       y = "Median Final Ticket Price",
       fill = "Purchase Method") +
  theme_minimal() +
  theme(legend.position = "right",
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    panel.grid.major.y = element_blank(), 
    panel.grid.major.x = element_line(color = "gray90"),
    plot.margin = unit(c(1, 1, 1, 1), "cm"))


Plot9

```


```{r}

#### Grouped Bar Charts -- Two Categorical Variables Against One Continuous Variable


### Analyzing Price Variations for Days of the Week


# When Days of the Week becomes a constant fill variable, 
# both 'Screening_Daypart' and 'Purchase_Method' produce zero insights
# since there is little to no price variation.

# When analyzing 'Ticket_Type' or 'Format', 
# new price variation insights are highlighted.


## 'Ticket_Type'

GroupedPlot1 <- ggplot(MovieTheaterDataSet, 
       aes(x = Ticket_Type, 
           y = Final_Ticket_Price, 
           fill = Day_of_the_Week)) +
  stat_summary(fun = "median", geom = "bar",
               position = position_dodge(width = 0.7), 
               color = "black", 
               width = 0.4) +  
  scale_fill_manual(values = c("Monday 1" = "#03045E", "Tuesday" = "#023E8A",    
    "Wednesday" = "#0077B6", "Thursday" = "#0096C7", "Friday" = "#00B4D8",     
    "Saturday" = "#48CAE4", "Sunday" = "#90E0EF", "Monday 2" = "#ADE8F4")) + 
  labs(title = "Median Final Ticket Price by Ticket Type and Day of the Week",
       x = "Ticket Type",
       y = "Median Final Ticket Price") +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
        axis.text.y = element_text(size = 9),  
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(color = "gray90"),
        legend.position = "none", 
        plot.margin = unit(c(1, 1, 1, 1), "cm"))


GroupedPlot1

# As you can see, outputs 'Admit One' and 'FC Promo' 
# exhibit the most price variation.

TicketTypeData <- MovieTheaterDataSet %>%
  filter(Ticket_Type %in% c("Admit One", "FC Promo"))


PVTicketType <- ggplot(TicketTypeData, 
                       aes(x = Ticket_Type, 
                           y = Final_Ticket_Price, 
                           fill = Day_of_the_Week)) +
  stat_summary(fun = "median", geom = "bar", 
               position = position_dodge(width = 0.7), 
               color = "black", width = 0.4) +
  scale_fill_manual(values = c("Monday 1" = "#03045E", "Tuesday" = "#023E8A",
                               "Wednesday" = "#0077B6", "Thursday" = "#0096C7",
                               "Friday" = "#00B4D8", "Saturday" = "#48CAE4",
                               "Sunday" = "#90E0EF", "Monday 2" = "#ADE8F4")) +
  labs(title = "Median Final Ticket Price: Admit One and FC Promo by Day",
       x = "Ticket Type",
       y = "Median Final Ticket Price",
       fill = "Day of the Week") +
  theme_minimal() +
  theme(axis.text.x = element_text(
    size = 10, angle = 0, hjust = 0.5),  
    axis.text.y = element_text(size = 9), 
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_line(color = "gray90"),
    legend.position = "none", 
    plot.margin = unit(c(1, 1, 1, 1), "cm"))

 PVTicketType 

 # Conducting a T-test can allow us to investigate whether the 
 # difference between 'Admit One' and 'FC Promo' is statistically
 # significant and not due to random chance.
 
AdmitOneData <- subset(MovieTheaterDataSet, Ticket_Type == "Admit One")
FCPromoData <- subset(MovieTheaterDataSet, Ticket_Type == "FC Promo")
t.test(AdmitOneData$Final_Ticket_Price,
       FCPromoData$Final_Ticket_Price,
       var.equal = FALSE)



## Format

GroupedPlot2 <- ggplot(MovieTheaterDataSet, 
                       aes(x = Format, 
                           y = Final_Ticket_Price, 
                           fill = Day_of_the_Week)) +
  stat_summary(fun = "median", geom = "bar", 
               position = position_dodge(width = 0.6), 
               color = "black", width = 0.5) +
  scale_fill_manual(values = c("Monday 1" = "#6A040F", "Tuesday" = "#9D0208",
                               "Wednesday" = "#D00000", "Thursday" = "#DC2F02",
                               "Friday" = "#E85D04", "Saturday" = "#F48C06",
                               "Sunday" = "#FAA307", "Monday 2" = "#FFBA08")) +
  labs(title = "Median Final Ticket Price by Format and Day of the Week",
       x = "Format", 
       y = "Median Final Ticket Price",
       fill = "Day of the Week") +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 9), 
        axis.text.y = element_text(size = 9), 
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(color = "gray90"),
        legend.position = "none",
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "cm"))


 GroupedPlot2

 # Only output '3D' exhibits meaningful price variation.
 # You will also notice this price variation is 
 # day-specific and appears as if the Ticket Price
 # is decreasing over the course of time.
 
 # A line chart can help visualize the passage of time.
 
MovieTheaterDataSet$Is3D <- 
  ifelse(MovieTheaterDataSet$Format == "3D", "3D", "Non-3D")

FormatData <- MovieTheaterDataSet %>%
  filter(Format %in% c("3D", "Non-3D"))

LC3DPlot <- ggplot(FormatData, 
                    aes(x = Day_of_the_Week, 
                        y = Final_Ticket_Price, 
                        group = Is3D, 
                        color = Is3D)) +
  stat_summary(fun = "median", geom = "line", size = 1.2) +
  stat_summary(fun = "median", geom = "point", size = 3) +
  scale_color_manual(values = c("3D" = "#6A0DAD", "Non-3D" = "#DDA0DD")) +
  labs(title = "Trend in Median Final Ticket Price: 3D vs. Non-3D Formats",
       x = "Day of the Week",
       y = "Median Final Ticket Price",
       color = "Format") +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 9),
        axis.text.y = element_text(size = 9),
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(color = "gray90"),
        legend.position = "right")



LC3DPlot
 
 # Conducting a T-test can allow us to investigate whether the 
 # difference between '3D' and 'Non-3D' is statistically
 # significant and not due to random chance.

FormatDataFiltered <- MovieTheaterDataSet %>%
  filter(Is3D %in% c("3D", "Non-3D"))
t.test(Final_Ticket_Price ~ Is3D,
       data = FormatDataFiltered,
       var.equal = FALSE)




```




# Econometrics

```{r}
#### Multi-Linear Regression

### Variables of interest include 'Screening_Daypart', 'Time_Periods', 'Genre', 'Day_of_the_Week', 'Format', 'Ticket_Type', 'Base_Ticket_Price', 'Purchase_Method', 'Discounted_Ticket', 'Special_Event_Pricing', 'Special_Program', and 'Age_Rating'.

# These variables may or may not be included in the Final Regression Model.

# We must make the determination as to whether certain variables of interest might be eliminated from the model.


### Variables of Concern include: 'Time_Periods', Special_Program'.

# Both 'Time_Periods' and 'Special_Program' are variables that are highly related to other variables: 'Screening_Daypart' and 'Special_Event_Pricing', respectively.

# We can test for multicollinearity within both variables.

# We calculated the correlation between 'Time_Periods' and 'Screening_Daypart':
MovieTheaterDataSet$Time_Periods_Num <- as.numeric(as.factor(MovieTheaterDataSet$Time_Periods))
MovieTheaterDataSet$Screening_Daypart_Num <- as.numeric(as.factor(MovieTheaterDataSet$Screening_Daypart))
Correlation_tp_sd <- cor(MovieTheaterDataSet$Time_Periods_Num,
                         MovieTheaterDataSet$Screening_Daypart_Num,
                         use = "complete.obs" )
Correlation_tp_sd

# A correlation of 0.89 indicates there is a strong positive linear relationship between both variables. 0.89 > 0.7 threshold for multicollinearity.
# In this instance we would ELIMINATE 'Time_Periods' in favor of 'Screening_Daypart' as the latter has better predictive power.


# We must do the same for 'Special_Program' and 'Special_Event_Pricing':
MovieTheaterDataSet$Special_Program_Num <- as.numeric(as.factor(MovieTheaterDataSet$Special_Program))
MovieTheaterDataSet$Special_Event_Pricing_Num <- as.numeric(as.factor(MovieTheaterDataSet$Special_Event_Pricing))
Correlation_sp_sep <- cor(MovieTheaterDataSet$Special_Program_Num,
                          MovieTheaterDataSet$Special_Event_Pricing_Num, 
                          use = "complete.obs")
Correlation_sp_sep

# A correlation of 0.29 indicates a weak positive linear relationship between both variables. 0.29 < 0.7 threshold for multicollinearity.
# While there is No Multicollinearity, the sample sizes within 'Special_Program' are imbalanced and inadequate for the Regression Model.
SpecialProgramCount
# In this instance we would ELIMINATE 'Special_Program' as the variable has no practical significance. 



### Single-Factor ANOVA Tests

VariableOfInterest <- c("Screening_Daypart", "Genre", 
                        "Day_of_the_Week", "Format", 
                        "Ticket_Type", "Base_Ticket_Price", 
                        "Purchase_Method", "Discounted_Ticket", 
                        "Special_Event_Pricing", "Age_Rating")

run_anova <- function(variable) {
  formula <- as.formula(paste("Final_Ticket_Price ~", variable))
  anova_result <- aov(formula, data = MovieTheaterDataSet)
  cat("\nANOVA for", variable, ":\n")
  print(summary(anova_result))
}

SingleFactorAnovaOutput <- capture.output(lapply(VariableOfInterest, run_anova))
writeLines(SingleFactorAnovaOutput, "anova_results.txt")




### Multi-Factor ANOVA Tests


# Multi-Factor ANOVA tests can be used to examine 
# combined effects variables have on the Final_Ticket_Price.
anova_formula <- Final_Ticket_Price ~ Screening_Daypart + Genre + Day_of_the_Week +
  Format + Ticket_Type + Base_Ticket_Price + Purchase_Method +
  Discounted_Ticket + Special_Event_Pricing + Age_Rating

multi_factor_anova <- aov(anova_formula, data = MovieTheaterDataSet)

summary(multi_factor_anova)


### The Big Picture

## Strongest Predictors (From High to Low F-Values)
# ("Purchase_Method","Base_Ticket_Price", 
# "Ticket_Type", "Format", "Screening_Daypart")

## Moderate Predictors
# ("Genre","Day_of_the_Week")

## Marginal Predictors
# ("Age_Rating")

## Insignificant Predictors
# ("Discounted_Ticket", 
#  "Special_Event_Pricing(???)")



### Interaction Effects


## Exploring Format:Day_of_the_Week

anova_interaction1 <- aov(Final_Ticket_Price ~ Format * Day_of_the_Week,
                          data = MovieTheaterDataSet)
summary(anova_interaction1)

# The interaction between both variables is not statistically significant.
# Do NOT include in the final regression model. 



## Exploring Screening_Daypart:Format

anova_interaction2 <- aov(Final_Ticket_Price ~ Screening_Daypart * Format, 
                          data = MovieTheaterDataSet)
summary(anova_interaction2)

# The interaction between both variables is statistically significant.
# Include in the final regression model.



## Exploring Ticket_Type:Purchase_Method

anova_interaction3 <- aov(Final_Ticket_Price ~ Ticket_Type * Purchase_Method,
                          data = MovieTheaterDataSet)
summary(anova_interaction3)

# The interaction between both variables is not statistically significant.
# DO NOT include in the final regression model.



## Exploring Genre:Screening_Daypart

anova_interaction4 <- aov(Final_Ticket_Price ~ Genre * Screening_Daypart,
                          data = MovieTheaterDataSet)
summary(anova_interaction4)

# The interaction between both variables is statistically significant.
# Include in the final regression model.



## Exploring Special_Event_Pricing:Day_of_the_Week

anova_interaction5 <- aov(Final_Ticket_Price ~ Special_Event_Pricing * Day_of_the_Week,
                          data = MovieTheaterDataSet)
summary(anova_interaction5)

# The interaction between both variables is statistically significant.
# Include in the final regression model.


## Final Interaction Terms
# Statistically significant: (Screening_Daypart:Format,
#                             Genre:Screening_Daypart,
#                             Special_Event_Pricing:Day_of_the_Week)
# NOT statistically significant (Exclude): (Format:Day_of_the_Week,
#                                            Ticket_Type:Purchase_Method)



### Final List of Variables


## Continuous Variables
# Base_Ticket_Price


## Categorical Variables
# Screening_Daypart
# Genre
# Day_of_the_Week
# Format
# Ticket_Type
# Purchase_Method
# Special_Event_Pricing
# Discounted_Ticket
# Age_Rating


## Interaction Terms
# Screening_Daypart:Format
# Genre:Screening_Daypart
# Special_Event_Pricing:Day_of_the_Week



### Final Regression Model


FinalRegressionModel <- lm(Final_Ticket_Price ~ 
                             Screening_Daypart + Genre + Day_of_the_Week + 
                             Format + Ticket_Type + Base_Ticket_Price + 
                             Purchase_Method + Special_Event_Pricing + 
                             Discounted_Ticket + Age_Rating + 
                             Screening_Daypart:Format + 
                             Genre:Screening_Daypart +
                             Special_Event_Pricing:Day_of_the_Week,
                           data = MovieTheaterDataSet)

summary(FinalRegressionModel)




## Model Accuracy

# Basic Distribution of Final_Ticket_Price
hist(MovieTheaterDataSet$Final_Ticket_Price,
     breaks = 20,
     col = "lightblue",
     border = "black",
     main = "Distribution of Final Ticket Prices",
     xlab = "Final Ticket Price ($)",
     ylab = "Frequency")


# Residual vs. Fitted Plot
plot(FinalRegressionModel, which = 1) 



# QQ Plot
plot(FinalRegressionModel, which = 2) 


# Predicted vs Actual Plot
MovieTheaterDataSet$Predicted_Price <- predict(FinalRegressionModel, newdata = MovieTheaterDataSet)

ggplot(MovieTheaterDataSet, aes(x = Final_Ticket_Price, y = Predicted_Price)) +
  geom_point(alpha = 0.5, color = "blue") +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "red") +  
  labs(title = "Predicted vs. Actual Ticket Prices",
       x = "Actual Final Ticket Price",
       y = "Predicted Final Ticket Price") +
  theme_minimal()



## Other Visualizations

# Interaction Effect Between Screening Daypart & Format
InteractionPlot1 <- ggplot(MovieTheaterDataSet, 
                           aes(x = Screening_Daypart, 
                               y = Final_Ticket_Price, 
                               fill = Format)) +
  stat_summary(fun = "median", geom = "bar", 
               position = "dodge", color = "black", width = 0.6) +
  scale_fill_manual(values = c("Standard" = "#004E89",  
                               "3D" = "#E89005",        
                               "DPX" = "#F42B03")) +  
  labs(title = "Interaction Effect: Screening Daypart & Format",
       x = "Screening Daypart",
       y = "Median Final Ticket Price",
       fill = "Format") +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 11),
        axis.text.y = element_text(size = 11),
        legend.position = "right")

InteractionPlot1



# Interaction Effect Between Genre & Screening Daypart
InteractionPlot2 <- ggplot(MovieTheaterDataSet, 
                           aes(x = Genre, 
                               y = Final_Ticket_Price, 
                               fill = Screening_Daypart)) +
  stat_summary(fun = "median", geom = "bar", 
               position = "dodge", color = "black", width = 0.8) +
  scale_fill_manual(values = c("Matinee" = "#FFD700",  
                               "Evening" = "#4682B4")) +  
  labs(title = "Interaction Effect: Genre & Screening Daypart",
       x = "Genre",
       y = "Median Final Ticket Price",
       fill = "Screening Daypart") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 35, hjust = 1, size = 10),
        axis.text.y = element_text(size = 11),
        legend.position = "right")

InteractionPlot2



# Interaction Effect Between Special Event Pricing & Day of the Week
InteractionPlot3 <- ggplot(MovieTheaterDataSet, 
                           aes(x = Day_of_the_Week, 
                               y = Final_Ticket_Price, 
                               fill = Special_Event_Pricing)) +
  stat_summary(fun = "median", geom = "bar", 
               position = "dodge", color = "black", width = 0.8) +
  scale_fill_manual(values = c("Yes" = "#F20262", 
                               "No" = "#0052C4")) +  
  labs(title = "Interaction Effect: Special Event Pricing & Day of the Week",
       x = "Day of the Week",
       y = "Median Final Ticket Price",
       fill = "Special Event Pricing") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 35, hjust = 1, size = 10),
        axis.text.y = element_text(size = 11),
        legend.position = "right")

InteractionPlot3



# Interaction Effect Between Format & Day of the Week
InteractionPlot4 <- ggplot(MovieTheaterDataSet, 
       aes(x = Day_of_the_Week, 
           y = Final_Ticket_Price, 
           fill = Format)) +
  stat_summary(fun = "median", geom = "bar", 
               position = "dodge", color = "black") +
  scale_fill_manual(values = c("Standard" = "#4CC9F0",   
                               "3D" = "#F72585",         
                               "DPX" = "#3A0CA3")) +     
  labs(title = "Interaction Effect: Format & Day of the Week",
       x = "Day of the Week",
       y = "Median Final Ticket Price",
       fill = "Format") +
  theme_minimal()

InteractionPlot4





```






